FROM php:7.2-fpm
ENV DEBIAN_FRONTEND=noninteractive
ENV SITE_NAME=local.streetartwork.com

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get install -y bash \
    libfreetype6-dev \
    libmcrypt-dev \
    zlib1g-dev \
    libicu-dev \
    g++ \
    apt-transport-https \
    zip \
    unzip \
    libxml2-dev \
    wget \
    vim \
    git \
    libmemcached-dev \
    libpq-dev

RUN docker-php-ext-install -j$(nproc) iconv \
    bcmath \
    mbstring \
    pdo \
    pdo_pgsql

RUN docker-php-ext-configure intl && docker-php-ext-install intl \
    zip \
    soap

RUN apt-get update && apt-get install -y \
            libfreetype6-dev \
            libjpeg62-turbo-dev \
            libpng-dev \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd

RUN apt-get update && apt-get install -y \
        libmagickwand-dev --no-install-recommends

RUN pecl install imagick && docker-php-ext-enable imagick

RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host=172.18.0.4" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_log=/var/log/xdebug_remote.log" >> /usr/local/etc/php/conf.d/xdebug.ini

# install openssl
#RUN apk add --no-cache openssl
RUN apt-get -y install openssl

# create a folder for the keys
#RUN mkdir /etc/nginx/ssl

#COPY ./docker/streetartlocal.com.key /var/ssl/streetartlocal.com.key
#COPY ./docker/streetartlocal.com.crt /var/ssl/streetartlocal.com.crt

#COPY ./streetartlocal.com.key /etc/nginx/ssl/
#COPY ./streetartlocal.com.crt /etc/nginx/ssl/

# generate the keys for your local domain
#RUN openssl genrsa -out "/var/ssl/streetartlocal.com.key" 2048 \
#    && openssl req -new -key "/var/ssl/streetartlocal.com.key" -out "/var/ssl/streetartlocal.com.crt" -subj "/CN=streetartlocal.com/O=streetartlocal.com/C=UK" \
#    && openssl x509 -req -days 365 -in "/var/ssl/streetartlocal.com.crt" -signkey "/var/ssl/streetartlocal.com.key" -out "/var/ssl/streetartlocal.com.crt"

RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer global require "hirak/prestissimo:^0.3"

RUN mkdir /app
WORKDIR /app

EXPOSE 9000
